### ISSUE TITLE
Multiple deployments: change commands to read state via command

### ISSUE THREAD

**Issue by endor** [milliHQ/terraform-aws-next-js#196]
Currently for commands such as `list-deployments` or `delete-deployment`, we are expecting a file `terraform.config.json` to exist. This is inconvenient for developers. The workflow that I currently have in mind would expect developers to enter the directory where they host their main terraform module and in there run something like `npx tf-next list-deployments`, which would internally run `terraform show -json` and read the info from there. We could also offer an alternative, where the developer provides a `--state` flag and passes the state in via `terraform show -json | npx tf-next list-deployments --state`. 

All of the above approaches are still not ideal, because passing the whole TF state including all the secrets etc. to the tool is not great from a security perspective.

Passing the dynamoDB table explicitly to the `list-deployments` command would also be an option, but is also kind of awkward for developers. The `delete-deployment` command needs a lot more arguments still, so it's really not a good option, unless we also move the deletion into a lambda and let it be triggered via file creation in a bucket.

**Comment by ofhouse** [comment]
# Idea (as discussed)

1. Terraform creates a new `deployment-config.json` file with the values needed for the CLI.
2. The file is then stored as object in S3. 
3. The CloudFront distribution gets a new custom behavior that bypasses the proxy (e.g. `/_next/_tf-next/deployment-config.json`) where the file is served from
4. When running the CLI, the domain (or an alias) must be provided, e.g. `tf-next list-deployments example.com`
5. The CLI then fetches the config example.com/_next/_tf-next/deployment-config.json and is able to perform the lookup without need to check the Terraform state.

**Comment by endor** [comment]
That deployment config should also at least contain the region and the proxy config table.
