### ISSUE TITLE
Question about the Multiple deployments

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [milliHQ/terraform-aws-next-js#209]
@endor @ofhouse Hello, I have a question regarding the code that determines which deployment a request is for when the proxy function receives a request.

https://github.com/milliHQ/terraform-aws-next-js/blob/443c65aeb90b01fdc68cd9e585d5ceba40c04e1f/packages/proxy/src/handler.ts#L101

Above line in the proxy module looks like the code that expects `hostHeader` to be a sub domain of `domainName`.
However, this code does not work on my side because `hostHeader` value is the s3 deploy bucket domain like `next-tf-static-deploy20210919151350851300000007.s3.us-west-2.amazonaws.com`.

This code running on the lambda@edge `origin request` does not know the domain on the user side. Should I solve it by adding a viewer request?

If I misunderstood, please let me know how are you currently testing the deployment created with `create-deployment` ?

**Comment by ofhouse** [comment]
The `Host` header can be piped to an `origin request` without the need for using `viewer request` for it.
However `Host` header must be whitelisted in the CloudFront behavior.

There is an ongoing PR for piping the original client Host header to the Lambda which also uses this technique: https://github.com/milliHQ/terraform-aws-next-js/pull/161

I've already validated that it works, PR needs some final touches, so I should be able to merge this soon.

**Comment by endor** [comment]
With this configuration the original `Host` header comes through to the proxy lambda correctly for me:

```Terraform
  cloudfront_origin_headers    = ["Host"]
  cloudfront_cache_key_headers = ["Host"]
  domain_name                  = var.domain
  multiple_deployments         = true
```

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@endor @ofhouse How about adding the above settings by default?

**Comment by ofhouse** [comment]
Yes, host header will be added to the default list, but needs to be added to the `cache_key_headers` instead of `origin_headers` otherwise CloudFront would output the same cached content for different domains.

My plan is to pick this up in #161 (Since it need some testing that ensures that the Host header is always modified in the proxy when the setting is active) this weekend and release a new version on the 0.9.x branch from it and then backport this change to the current main.
