### ISSUE TITLE
Dynamic routing

### ISSUE THREAD

**Issue by qpre** [milliHQ/terraform-aws-next-js#218]
Hello,

When using the module in versions 1.0.0-canary.1 or 0.9.2 and the latest `tf-next` package dynamic routing does not work out of the box.

`https://xxx.cloudfront.com/user/1` -> 404
`https://xxx.cloudfront.com/user/[user_id]` -> renders `pages/users/[user_id]/index.js`

I've seen https://github.com/milliHQ/terraform-aws-next-js/issues/16 but it seemed resolved, are they any configuration steps that I might be missing ?

**Comment by qpre** [comment]
turns to that it works if I add a `getServerSideProps` to all routes under `[user_id]`, but it does not seem very efficient :)

**Comment by ofhouse** [comment]
Hi, dynamic routes are fully supported by the module and are also covered by e2e tests.
Difficult to say what's wrong in your case without looking at the actual code.

Are you using [Incremental Static Regeneration (ISR)](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration) to render the pages?
ISR is unfortunately not supported by the module #11.

**Comment by qpre** [comment]
Hello again, sincerely sorry that I did not include enough details in my report !

my `next.config.js`:

```
const withSvgr = require('next-svgr');

module.exports = withSvgr({
  async rewrites() {
    return [
      {
        source: '/robots.txt',
        destination: '/api/robots',
      },
    ];
  },

  async redirects() {
    return [
      {
        source: '/workspace/:workspace_id',
        destination: '/workspace/:workspace_id/home',
        permanent: true,
      },
    ];
  },
});
```

and the terraform config:

```
module "tf_next" {
  source = "milliHQ/next-js/aws"
  version = "1.0.0-canary.1"

  providers = {
    aws.global_region = aws.us-east-1
  }

  deployment_name = "app-${var.environment}"

  cloudfront_aliases             = [var.domain, "*.${var.domain}"]
  cloudfront_acm_certificate_arn = aws_acm_certificate.us-east-1.arn

  next_tf_dir = "${path.root}/../../../../app/browser/.next-tf"
}
```

using `next@11.1.2` and `tf-next@1.0.0-canary.1`

I'll put together a reproduction repo if I have the time but that might not be until next week.

**Comment by ofhouse** [comment]
No problem, thanks for providing more details 👍
Config (both Next.js and Terraform) looks fine.

I would recommend to use `0.9.2` for now, since `1.0.0-canary.1` is an early development version that contains a new feature that enables multiple deployments.
The feature is not ready for use at the moment and it's likely that the version contains bugs.

What's more interesting than the config is probably the content of the `pages/users/[user_id]/index.js` file.
Especially whether the [`getStaticProps`](https://nextjs.org/docs/basic-features/data-fetching#getstaticprops-static-generation) & [`getStaticPaths`](https://nextjs.org/docs/basic-features/data-fetching#getstaticpaths-static-generation) functions are used and what they return.

**Comment by oliverdendis** [comment]
I have the same issues for dynamic routes (`getServerSideProps` or `getStaticPaths` are not used) on `0.9.2`

**Comment by ofhouse** [comment]
@oliverdendis Thanks for reporting.
Can you provide the path to the file inside the `pages` (e.g. `pages/users/[user_id]/index.js`) directory where the routing fails for?

**Comment by ofhouse** [comment]
Okay, can confirm that there is a bug that prevents access to pages when the directory contains a dynamic part.

**Comment by ofhouse** [comment]
Started working on a fix for the problem, but it will likely not be released before the weekend.

**Comment by qpre** [comment]
awesome thanks @ofhouse ! ping me if you need testing on other projects
