### ISSUE TITLE
NPM package version outdated

### ISSUE THREAD

**Issue by rob-mccann** [milliHQ/terraform-aws-next-js#222]
Hello! I noticed the npm version is currently at 0.7.0 where the repo is at 0.9.2. I just wanted to check if that was intentional?

**Comment by rob-mccann** [comment]
terraform release != npm release

**Comment by ofhouse** [comment]
Yes, the version numbers of the npm modules and terraform module are currently independent.

However since this caused some confusion in the past, we will start publishing a unified version number across all packages beginning with the upcoming `v0.10.0` release.
