### ISSUE TITLE
Support for generic app SQS handlers

### ISSUE THREAD

**Issue by kontinuity** [milliHQ/terraform-aws-next-js#223]
In my app, I need to handle SQS webhooks the code for which is part of the same repo. How could I extend the current TF package to:
* Deploy the code as another lambda not integrated to APIGW
* Reuse the code zip that is generated if possible

Thanks!

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
