### ISSUE TITLE
[Question] Are catch-all routes and optional catch-all routes supported?

### ISSUE THREAD

**Issue by kylemh** [milliHQ/terraform-aws-next-js#234]
I think this would fall under dynamic routing, but I didn't want to be presumptuous as I evaluate this tool!

**Comment by ofhouse** [comment]
Hi, thanks for reaching out.

Yes, [catch-all](https://nextjs.org/docs/routing/dynamic-routes#catch-all-routes) (`pages/post/[...slug].js`) and [optional catch-all](https://nextjs.org/docs/routing/dynamic-routes#optional-catch-all-routes) routes are fully supported by the module. 👍
