### ISSUE TITLE
Error in API Lambdas on request  

### ISSUE THREAD

**Issue by jatidevelopments** [milliHQ/terraform-aws-next-js#237]
Hi everyone,
I have a problem when deploying to AWS with my api routes. Did anybody experienced the same issue? Maybe its because I run "npx tf-next build" from MacOS? Does anybody have an idea how I can fix it? 

Error log from Cloudwatch for NEXT_API_LAMBDA_0: 

<img width="1146" alt="Screenshot 2021-11-12 at 22 53 59" src="https://user-images.githubusercontent.com/58979465/141648378-8dd0bf68-7b38-4e28-adb6-99a74278b4cf.png">

Error in Dev Tools --> Network on request: 

<img width="583" alt="Screenshot 2021-11-12 at 22 54 28" src="https://user-images.githubusercontent.com/58979465/141648402-2499620f-a0ac-4607-8ea7-81233af0ee61.png">

**Comment by ofhouse** [comment]
Yes it looks like your local build runtime (MacOS) installs dependencies for another architecture than what Lambda uses internally.

When using npm you could workaround this by adding the `--target_arch` & `--target_platform` flags:
```sh
npm i --target_arch=x64 --target_platform=linux
```

And then run the build command with the `--skipDownload` (Uses the local dependencies downloaded from the `npm i` command):
```
npx tf-next build --skipDownload
```

Note that yarn does not offer an option to define `target_arch` & `target_platform` manually.

---

A better solution would be to run the build command in a CI environment that mimics the Lambda runtime.
Good candidate here would be a Docker based runner with [`public.ecr.aws/sam/build-nodejs14.x:latest`](https://gallery.ecr.aws/sam/build-nodejs14.x) image.
You can find a full list of build images for Lambda here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html

**Comment by jatidevelopments** [comment]
> Yes it looks like your local build runtime (MacOS) installs dependencies for another architecture than what Lambda uses internally.
> 
> When using npm you could workaround this by adding the `--target_arch` & `--target_platform` flags:
> 
> ```shell
> npm i --target_arch=x64 --target_platform=linux
> ```
> 
> And then run the build command with the `--skipDownload` (Uses the local dependencies downloaded from the `npm i` command):
> 
> ```
> npx tf-next build --skipDownload
> ```
> 
> Note that yarn does not offer an option to define `target_arch` & `target_platform` manually.
> 
> A better solution would be to run the build command in a CI environment that mimics the Lambda runtime. Good candidate here would be a Docker based runner with [`public.ecr.aws/sam/build-nodejs14.x:latest`](https://gallery.ecr.aws/sam/build-nodejs14.x) image. You can find a full list of build images for Lambda here: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-image-repositories.html

Cheers! Made the deployment work with AWS Cloud9.
