### ISSUE TITLE
Split Build Files from Terraform Code

### ISSUE THREAD

**Issue by aaronbarnaby** [milliHQ/terraform-aws-next-js#242]
Hi,

I was wondering if there is a way to use this terraform module if the artifact files (usually in .next-tf) wasn't part of the terraform.
Ideally the files within .next-tf would be uploaded to a S3 project from a separate solution and then in our terraform code solution it can be referenced the bucket (and prefix key) path for there the files are.

**Comment by ofhouse** [comment]
Hi, this would probably work today.
You could create an initial deployment first and then uploading the `static-files.zip` & `proxy-config.json` manually to S3.

You simply would have to find out the bucket names of this two buckets (1 & 2):
![Screenshot 2021-11-25 at 18 31 16](https://user-images.githubusercontent.com/472867/143483239-8f1176e1-a13f-40d2-a56f-dfc5a3c330a4.png)

The only thing is that the Terraform state and the `proxy-config.json` will be out of sync after the first manual deployment.
The `static-files.zip` is not tracked by Terraform (And is also deleted after successful deployment).

**Comment by aaronbarnaby** [comment]
thanks this answers what I needed to know to deal with my issue :)
