### ISSUE TITLE
`create_image_optimization` breaks because of breaking change in the newest 12.0.0 release

### ISSUE THREAD

**Issue by mohalsherif** [milliHQ/terraform-aws-next-js#243]
Since a few hours ago, the new `terraform-aws-next-js-image-optimization` module was released, the feature `create_image_optimization` is currently broken. 

There are two possible fixes, either
- (1) hardcode the version to something like the following: version = ">= 11.0.0, < 12.0.0" 
- (2) replace the deprecated variable with the update variable (i.e. replace `cloudfront_origin_image_optimizer` with `cloudfront_origin`)

The pull request of (2) will follow and please merge if possible

**Comment by ofhouse** [comment]
Thanks for the report.
Thought that I had already replaced the deprecated output in the module, sorry for the trouble 🙈

Will merge your fix shortly and release it as `v0.10.2`, thanks for the PR 👍

**Comment by ofhouse** [comment]
This is now fixed in the `v0.10.2` release: https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.10.2
