### ISSUE TITLE
[QUESTION] Pass data to lambdas or avoid lambdas 

### ISSUE THREAD

**Issue by mohalsherif** [milliHQ/terraform-aws-next-js#249]
We currently use an next-i18next solution for localisation.

We face an issue, because the page Lambda does not have access to the `public` folder, like we have during build and hence can not get hold of the `public/locales` folder.

We see two possible solutions that don't quite seem implemented here:

1- Avoid calling lambdas all together, so do not use [Incremental Static Regeneration](https://vercel.com/docs/concepts/next.js/incremental-static-regeneration). 
2- Pass some data to the lambda functions such that they have access to the public folder.

For 1)
It looks like we call the lambda here independent if we have `revalidate` set or not for the `getStaticProps` function for any page. Based on [data fetching concepts in nextjs](https://nextjs.org/docs/basic-features/data-fetching#statically-generates-both-html-and-json), output of `getStaticProps` should not be precomputed (incase no ISR is in play). Is this a bug?

For 2) 
It seems like there is a way to start the lambdas with an EBS volume attached, but not directly supported in this terraform module. Is this even a good idea?

**Comment by mohalsherif** [comment]
OK. The solution was to add
`localePath: path.resolve("./public/locales"),` to the i18 config.

I will not delete this maybe for reference for others.

**Comment by ofhouse** [comment]
Thanks for sharing!

The builder internally uses [nft](https://github.com/vercel/nft) to determine files that should be added to the bundle to keep the size of the Lambda package as small as possible.
nft checks the content of the files for references, so only files that are called by reference (e.g. `path.resolve("./public/locales")`) are then included in the bundle.
