### ISSUE TITLE
Error during deployment regarding concurrency

### ISSUE THREAD

**Issue by mvanaltvorst** [milliHQ/terraform-aws-next-js#251]
Thank you for this project, it is precisely what I was looking for. However, I encounter an error when I try to deploy a basic configuration:
```
╷
389
│ Error: error setting Lambda Function (tf-next_tfn-deploy) concurrency: InvalidParameterValueException: Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50].
390
│ {
391
│   RespMetadata: {
392
│     StatusCode: 400,
393
│     RequestID: "005a79fe-c425-4a34-98e2-61d39be18bf3"
394
│   },
395
│   Message_: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [50]."
396
│ }
397
│ 
398
│   with module.tf_next.module.statics_deploy.module.deploy_trigger.aws_lambda_function.this[0],
399
│   on .terraform/modules/tf_next.statics_deploy.deploy_trigger/main.tf line 14, in resource "aws_lambda_function" "this":
400
│   14: resource "aws_lambda_function" "this" {
401
│ 
402
╵
```

Have you encountered this error before, or do you know where I might be able to learn more about what might be causing this? Thank you.

**Comment by ofhouse** [comment]
Hey, sorry for the late answer.

Looks like this has something to do with other Lambda functions deployed to your AWS account.
Another issue from the Serverless framework provides some explanations why this error message might occur: https://forum.serverless.com/t/unreservedconcurrentexecution-below-its-minimum-value-of-100/10323/4

**Comment by khuezy** [comment]
I'm also getting this error playing w/ the free-tier. My account has `Full account concurrency` of 50, and the `proxy` lambda consumes 1, which brings it under the minimum value 50.

How does one reduce the minimum value?

**Comment by khuezy** [comment]
@mvanaltvorst Did you get this resolved? If not, you can request a quota increase on your main region:
https://us-west-2.console.aws.amazon.com/servicequotas/home/services/lambda/quotas/L-B99A9384

I think anything above 50 would work, but I requested 200 just to be sure.

**Comment by ofhouse** [comment]
Saw this today in a newly created AWS account too.

Looks like AWS drastically decreased the quota value here:
![Frame 1](https://user-images.githubusercontent.com/472867/152031311-754a1c08-0be7-4202-9660-e2dec29b803b.png)

Requesting an increase should work, will add this as a doc entry to the repo.

**Comment by ofhouse** [comment]
Added a support document for this issue here: [Function decreases account's UnreservedConcurrentExecution below its minimum value](https://github.com/milliHQ/terraform-aws-next-js/blob/main/docs/known-issues/0001_reserved-concurrent-executions.md)

Also pinged the AWS support about the issue here: https://twitter.com/milliHQ/status/1488592847825780743
