### ISSUE TITLE
error deleting Lambda Function on terraform destroy

### ISSUE THREAD

**Issue by Tsvetkovv** [milliHQ/terraform-aws-next-js#253]
I played around with [Terraform Next.js complete example](https://github.com/milliHQ/terraform-aws-next-js/tree/main/examples/complete) and on `terraform destroy` I got the next:
```
│ Error: error deleting Lambda Function (tf-next-example-complete_tfn-proxy): InvalidParameterValueException: Lambda was unable to delete arn:aws:lambda:us-east-1:236421390663:function:tf-next-example-complete_tfn-proxy:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "f764d0b1-0abc-4cf6-9d4e-7e206f60644b"
│   },
│   Message_: "Lambda was unable to delete arn:aws:lambda:us-east-1:236421390663:function:tf-next-example-complete_tfn-proxy:1 because it is a replicated function. Please see our documentation for Deleting Lambda@Edge Functions and Replicas."
│ }
```
Seems like only 3 resources are left:

- module.tf_next.module.proxy.module.edge_proxy.aws_cloudwatch_log_group.lambda[0]
- module.tf_next.module.proxy.module.edge_proxy.aws_iam_role.lambda[0]
- module.tf_next.module.proxy.module.edge_proxy.aws_lambda_function.this

running `terraform destroy` does not resolve the issue

### Workaround
I removed Lambdas manually via ([AWS Console](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions)) and run `terraform destroy` again.

version: 0.10.2

**Comment by khuezy** [comment]
Hi, what version are you using? There might be better error/retry handling in one of the newer 0.10.2 or 1.0.0 canary release.
This is a known issue in the readme file.

**Comment by Tsvetkovv** [comment]
ah, yeah, it is in readme. I tried to search by the error text and did not find. Thank you
p.s. version 0.10.2
