### ISSUE TITLE
Question: How to deal with Lambda environment variables?

### ISSUE THREAD

**Issue by syphernl** [milliHQ/terraform-aws-next-js#281]
Our application requires a few environment variables (e.g. Google Maps API key) to be available in the Pages Lambda. 
The preferable method would be Lambda pulling it from the SSM Parameter Store, however this needs to be done within the application (which is a bit in contrast with a service like ECS which does this for you)

Is there (currently) any way of doing this, besides setting explicit environment variables in the Lambda itself? 
IMHO this is an undesirable approach since these values could potentially contain secrets that should be added as `SecureString` to the SSM instead of "plain" as environment variable.

**Comment by ofhouse** [comment]
Hi, unfortunately there is currently no other way known to me than accessing SSM though the SDK on the application layer in Lambda.

Other services like Vault offer an official lambda extension for this use-case: https://github.com/hashicorp/vault-lambda-extension (However out module currently doesn't support extensions AFAIK).
AWS only provides a schematic description how this could be implemented: https://docs.aws.amazon.com/prescriptive-guidance/latest/patterns/cache-secrets-using-aws-lambda-extensions.html
