### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by nobletom123** [milliHQ/terraform-aws-next-js#289]
Hello,

I have just begun using this package. The terraform apply threw an initial error, the one mentioned in #235, however when running again was successful. However when navigating to the cloudfront domain I get a 503 error with:

`{"message":"Service Unavailable"}`

Would you have any suggestions for debugging this?

Below is my main.tf

```
# main.tf

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

locals {
  stage               = "dev"
  app_name            = "wp"
  project_name        = "int-admin-app"
  project_environment_variables = jsondecode(data.aws_secretsmanager_secret_version.environment_variables.secret_string)
}

# Main region where the resources should be created in
# (Should be close to the location of your viewers)
provider "aws" {
  region = "eu-west-2"
}

# Provider used for creating the Lambda@Edge function which must be deployed
# to us-east-1 region (Should not be changed)
provider "aws" {
  alias  = "global_region"
  region = "us-east-1"
}

module "tf_next" {
  source = "milliHQ/next-js/aws"

  lambda_environment_variables=local.project_environment_variables

  providers = {
    aws.global_region = aws.global_region
  }

}

data "aws_secretsmanager_secret_version" "environment_variables" {
  secret_id = "aws-deploy-${local.stage}/terraform-infrastructure-multicurrency/${local.app_name}-${local.stage}-${local.project_name}"
}

output "cloudfront_domain_name" {
  value = module.tf_next.cloudfront_domain_name
}
```

**Comment by khuezy** [comment]
Hi, it seems like the owner of this project is preoccupied with his primary work at the moment.

Have you tried referencing the examples on https://github.com/milliHQ/terraform-aws-next-js/tree/main/examples?
I recall having the Service Unavailable error when I first started my project.

IIRC, I had to set up the Route53 config in the `tf` and set up the custom name servers on my domain provider.

**Comment by ofhouse** [comment]
Hey @nobletom123,
sorry for the delay.

Your Terraform config seems fine.
Which version of Next.js do you use for your app?

**Comment by nobletom123** [comment]
Hello,
Very sorry for the late reply - we are using v12.1.0

Thanks

**Comment by nobletom123** [comment]
> Hi, it seems like the owner of this project is preoccupied with his primary work at the moment.
> 
> Have you tried referencing the examples on https://github.com/milliHQ/terraform-aws-next-js/tree/main/examples? I recall having the Service Unavailable error when I first started my project.
> 
> IIRC, I had to set up the Route53 config in the `tf` and set up the custom name servers on my domain provider.

Is this to mean I shouldn't rely on the cloudfront url generated at the end of the apply?

**Comment by ofhouse** [comment]
Seems like the error comes from Next.js here.
Could you check the CloudWatch logs of the Lambda if there is some more detailed error message?

**Comment by nobletom123** [comment]
> Seems like the error comes from Next.js here. Could you check the CloudWatch logs of the Lambda if there is some more detailed error message?

No I'm afraid not - the lambda seems to execute and complete without any error message. Part of the NextJS app uses as authentication provider, which I believe returns request headers larger than the 8192 (ish) bytes allowed by S3 - do you know if this would be the case as well, and whether or not this can be increased?

**Comment by ofhouse** [comment]
> When using getServerSideProps - I just get the error above - when the page is static, it will render however when authenticated, returns an error in XML, stating the request headers are too large.

We currently use under the hood HTTP API Gateway, which has a hard limit (cannot increased) of **10240 bytes** for the header: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html#http-api-quotas
This seems pretty massive for a request header, can you confirm that it exceeds this size by looking into the devTools of your browser?

You can check this by:
1. Open Network tab in DevTools -> Select the initial request -> Request Headers -> View Source
2. Then copy the whole content to a text editor of your choice and check how many characters (bytes) it has.
![Screenshot 2022-04-25 at 16 16 05](https://user-images.githubusercontent.com/472867/165108289-c7a9991f-e103-4c60-8751-59554b52f1a0.png)

**Comment by nobletom123** [comment]
So when checking the request headers, in total it is 9.2kb, so whilst large still under the 10.2kb threshold you mentioned.
Its weird - this issue only appears when authenticated, so can't really say - would cloudwatch lambda logs be the best place to look?

**Comment by nobletom123** [comment]
So apologies, this looks like it was me misreading the logs - the page lambda was actually timing out after 10 seconds, I increased it to 30 seconds and is now working as expected. 
Thanks for your support
