### ISSUE TITLE
Images not loading in the browser

### ISSUE THREAD

**Issue by rnpatel2611** [milliHQ/terraform-aws-next-js#294]
Hello,
I am facing an issue with some images not loading in the browser. Here is my technology stack.
- TF_next: v0.11.0
- NextJS: 12

I have been using this stack for the last 4 months with next js 12.  It's perfectly working fine till 20th March 2022. After that, I am facing an issue with load Images in the browser. Please check the screenshot. 
![Screenshot 2022-04-04 171839](https://user-images.githubusercontent.com/86233534/161537609-ad5c27e6-a064-4445-97f8-4ef8afba4b63.png)

So after this weird behavior of this tf-next stack, I have to move my application into the EC2 instance. It's working perfectly fine in EC2 instances and local systems. But I am very clueless about why this issue happens when I deploy an application using tf-next stack.

When I force to load an image from the browser or try to load an image from incognito mode, I am able to load that image but it's not able on first load in my website.  

Can you help to find what could be an issue here?

Thanks

**Comment by ofhouse** [comment]
Hi, thanks for reaching out.
Is there some error message in the network tab of the developer tools available?
![Screenshot 2022-04-04 at 19 46 02](https://user-images.githubusercontent.com/472867/161601703-7e2584f6-7fc0-4304-bdbe-32ce87ddd327.png)

**Comment by rnpatel2611** [comment]
Thanks for the quick reply. I am not getting any errors in the network tab. This is a very random issue. I am getting this once in 4-5 reload of pages in recommended properties section. 

When I try to load the image on right-click, I am able to load that image. If you like to check an issue, I am happy to share my UAT endpoint with you. https://uat-webv3.whimstay.com/

If you can check please try to check 3-4 times in-private window to reproduce if not reproduced at once. Thanks for your support, We are really stuck on this issue and we are not able to trace it. 

Thanks you

**Comment by rahulit1991** [comment]
Yes, that is intentionally added. As our static content is stored in an s3 bucket and served with CloudFront from the beginning. so we remain the same configuration for this stack as well. And the same configuration is working for the last 5 months.

Any clue, What could be an issue? And what action should I take to resolve this issue?

**Comment by khuezy** [comment]
Hard to debug w/o the logs. The resources loads when I put in the cloudfront link in my browser, but the _next/image?url=... shows a blank page.

I noticed the paths do not have an extension, but I'm just guessing at this point.

https://github.com/milliHQ/pixel/blob/304947cb84beb23ca4cd42ad6869d9c105c2be21/packages/express/lib/middleware.ts#L106

Maybe it's failing to get the correct file extension and causes some weird issue? But that doesn't explain why 1 of the images went through:

![image](https://user-images.githubusercontent.com/811298/161824427-4712f693-49bb-49ec-b3c7-540de492c055.png)

**Comment by ofhouse** [comment]
The image optimizer currently has an issue where processed images that are larger than 6mb cannot be sent back to the viewer (https://github.com/milliHQ/terraform-aws-next-js-image-optimization/issues/110).
But I doubt that this is the case here.

Next.js versions prior to `12.1.0` had a built-in local caching (where the processed image gets written to the hard disk).
Since each Lambda only has a local storage of 512 MB available this could be exceeded when a large amount of images are processed in a short period of time (< 1h).
But I also doubt that this could be the issue here.

The `12.1.0` release is currently incompatible with the module, but I plan to bring an update this week that includes this release.

Do you have anything special in your `next.config.js` in the image section?

**Comment by rahulit1991** [comment]
Nothing special in next.config.js. I am a little curious about this issue. It was working fine till we serve the original images before 20th March and I can see that we have images sized more than 10 MB and this stack is working absolutely fine. But after that, we enabled webpack and reduce the size of the s3 bucket. And then we have faced this issue. We disabled the again webpack but still, the issue remains the same. 

<img width="1192" alt="next config" src="https://user-images.githubusercontent.com/64314085/161877876-a7e8cc79-ef95-426e-9ea6-41af7032bb31.png">

**Comment by khuezy** [comment]
That's really strange, the images loads fine for me on Chrome but not in incognito mode (even after clearing cache).
It's having the same issue on Brave. It loads perfectly fine on MS Edge though.

**Comment by rahulit1991** [comment]
It's a random issue with any image and most of the images are lesser than 5 MB. I am facing an issue with an image size of about 100 KB as well.

**Comment by khuezy** [comment]
terraform:
`create_image_optimization: false`

Pass in the direct source (without the "_next/image") to the `<Image />` `loader` or omit it altogether.
```
function imageLoader({ src }) {
    return src
  }
```

**Comment by rahulit1991** [comment]
Thanks for your support. Don't know what could be an issue here but it's resolved with the latest version of this stack.
