### ISSUE TITLE
Add support for pnpm

### ISSUE THREAD

**Issue by ofhouse** [milliHQ/terraform-aws-next-js#309]
pnpm in `tf-next build` command is currently not supported.

## ToDo
- [x] Update `@vercel/build-utils`  
  Build utils already has support for recognising pnpm: https://github.com/vercel/vercel/blob/a400b9b29d171232f4649e67e1fdcf4fb8d6a4c8/packages/build-utils/src/fs/run-user-scripts.ts#L293
- [ ] Add e2e test for pnpm & pnpm monorepo

**Comment by RomainBillot** [comment]
Hi, can we get help on how to contribute to this one?
I'd really like to see this feature to be in :rocket:

**Comment by ofhouse** [comment]
This is now released in [`v0.13.1`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.13.1).
