### ISSUE TITLE
Error: External Program Lookup Failed

### ISSUE THREAD

**Issue by PranaySingh61** [milliHQ/terraform-aws-next-js#314]
Hello,
 I have done the setup as per read me, however it fails with the following error

![TF_Error](https://user-images.githubusercontent.com/105429767/168063663-e235b830-de9c-4b67-84de-2a4283b17865.PNG)

Can you please help

**Comment by ofhouse** [comment]
Hi,
the Terraform module needs [bash](https://en.wikipedia.org/wiki/Bash_(Unix_shell)) and [curl](https://curl.se/) installed to work properly.
Seems like bash is missing on your system:
```
Error: exec: "bash": executable file not found in $PATH
```

**Comment by ofhouse** [comment]
We have now added a new section [Prerequisites](https://github.com/milliHQ/terraform-aws-next-js#prerequisites) to the Readme of the project, that shows what software should be installed.
