### ISSUE TITLE
lambda_attach_to_vpc options is deprecated?

### ISSUE THREAD

**Issue by drselump14** [milliHQ/terraform-aws-next-js#328]
The variable still exists in `variable.tf` but can't find a single use of it on `main.tf`. Did we deprecate this option?

Tried to add it in an appropriate place PR #327 , but after applying with terraform, every deployment with `tf-next deploy` get failed (500 Error).

Any help/guidance would be appreciated

**Comment by ofhouse** [comment]
Answered in #327:

> Hi, thanks for reaching out.
> We are currently in a transition phase from `v0.x` to `v1.0.0` and the main branch currently contains a development version where not all features are available that were previously in `v0.x`.
> So we removed some settings from the `variable.tf` that will be no longer configurable through Terraform but later in the CLI.
>
> Features that are currently missing, are (incomplete list):
>
> - Environment variables for Lambda functions
> - Next.js image optimization
> - Attach VPC to Lambda functions
> - CloudFront invalidations
>
> To use these features we recommend using releases from the [`v0.x` branch](https://github.com/milliHQ/terraform-aws- next-js/tree/v0.x) (Latest release from it is [`v0.13.2`](https://github.com/milliHQ/terraform-aws-next-js/releases/tag/v0.13.2)) instead of using the `v1.0.0-canary` preview.
>
> I wrote a blog article with more details about the upcoming changes here: [Terraform Next.js: The road to Atomic Deployments](https://milli.is/blog/the-road-to-atomic-deployments)

**Comment by ofhouse** [comment]
I'm going to close this issue because it has been inactive for 30 days ⏳. This helps to find and focus on the active issues.
