### ISSUE TITLE
Dynamic API Route Failure

### ISSUE THREAD

**Issue by Jake-RoundrockIO** [milliHQ/terraform-aws-next-js#331]
After successfully deploying my Next.js application with the latest canary build (1.0.0-canary.4), it appears that the Cloudfront distribution/lambda proxy is unable to route to dynamic API routes. 

Specifically, we are using [Auth0](https://github.com/auth0/nextjs-auth0), which requires us to use the dynamic route `/pages/api/auth/[...auth0].js` for the authentication flow. When trying to access `<hostname>/api/auth/login` I am presented with a 404 message from cloudfront.

I've confirmed that when running the build locally, there is no issue reaching this endpoint.

### Environment
```
Node: v16.14.0
Next.js: v12.1.6
tf-next: v1.0.0-canary.4
```

**Comment by LarissaKim** [comment]
I'd been planning on using this to deploy a Next.js app that uses [NextAuth.js](https://github.com/nextauthjs/next-auth), which also requires a dynamic API route for the authentication flow (`/pages/api/auth/[...nextauth].js`).

Is there a solution/workaround for this, or are dynamic API routes not supported?

@Jake-RoundrockIO how did you end up handling authentication?
