### ISSUE TITLE
Question: Environment variables for Lambda functions

### ISSUE THREAD

**Issue by PodStuart** [milliHQ/terraform-aws-next-js#337]
I note that on your [blog post](https://milli.is/blog/the-road-to-atomic-deployments) you state that environment variables won't be currently working in the canary version. I just want to clarify what this means exactly. 

Does this just mean that there are currently no terraform variables which allow you to configure environment variables on the Lambda functions created during a `tf-next deploy`?

I'm asking as I am trying to get a Next.js API route to return an environment variable which I've manually configured on the Lambda via the AWS console. I'm doing this using publicRuntimeConfig. I'd have thought this would work OK but I just can't seem to get it to work. I'm probably doing something wrong.

**Comment by iarmankhan** [comment]
@ofhouse currently it seems like .env file is getting used automatically, can we configure it to use other .env files, like .env.staging or .env.qa ?

**Comment by ochoalopezalfredo** [comment]
> @ofhouse currently it seems like .env file is getting used automatically, can we configure it to use other .env files, like .env.staging or .env.qa ?

Using 

`NODE_ENV=staging tf-next build`
