### ISSUE TITLE
error putting S3 Bucket Notification Configuration

### ISSUE THREAD

**Issue by lesnitsky** [milliHQ/terraform-aws-next-js#348]
Sometimes I get this error after terraform apply:

```
╷
│ Error: error putting S3 Bucket Notification Configuration: InvalidArgument: Unable to validate the following destination configurations
│       status code: 400, request id: 6D9ANCDGTDAC2TN8, host id: f8gNGHqldgiFnyDpq4cLSYIKnyTmFz5Znmg3KI/tsM4aPMZCt9R9UCl6dziCOMHXrDSvt0ruIQ4=
│ 
│   with module.tf_next.module.statics_deploy.aws_s3_bucket_notification.on_create,
│   on .terraform/modules/tf_next/modules/statics-deploy/main.tf line 22, in resource "aws_s3_bucket_notification" "on_create":
│   22: resource "aws_s3_bucket_notification" "on_create" {
│ 
```

I wasn't able to figure out the conditions under which this error occurs.

**Comment by ofhouse** [comment]
Thanks for reporting, closing this as a known bug: https://github.com/milliHQ/terraform-aws-next-js/issues/138#issuecomment-864454823

Has something to do that we connect SQS and S3 triggers to the same Lambda which causes some race condition on AWS side.
This will be resolved once we ditch SQS for the invalidation queue.
